# Generated by Django 4.2.3 on 2023-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0002_rename_invoiced_costing_complete_on_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='order_in_list',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
