# Generated by Django 4.2.3 on 2023-12-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0003_categories_order_in_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costing',
            name='qs_claimed',
        ),
    ]
