# Generated by Django 4.2.3 on 2024-01-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0004_remove_costing_qs_claimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committed_quotes',
            fields=[
                ('quote', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Committed_allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_admin.costing')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_admin.committed_quotes')),
            ],
        ),
    ]
