# Generated by Django 4.2.3 on 2024-01-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0005_committed_quotes_committed_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committed_allocations',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
