# Generated by Django 4.2.3 on 2024-01-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0006_alter_committed_allocations_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='committed_quotes',
            name='supplier',
            field=models.CharField(default='placey', max_length=100),
            preserve_default=False,
        ),
    ]
