# Generated by Django 4.2.3 on 2024-01-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0007_committed_quotes_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costing',
            name='committed',
        ),
    ]
