# Generated by Django 4.2.3 on 2024-01-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0010_claims_claim_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='pdf',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
