# Generated by Django 4.2.3 on 2024-01-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0011_claims_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim_allocations',
            name='associated_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_admin.committed_quotes'),
        ),
    ]
