# Generated by Django 4.2.3 on 2024-01-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0012_claim_allocations_associated_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
