# Generated by Django 4.2.3 on 2024-01-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0013_alter_costing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hc_claims',
            fields=[
                ('hc_claim', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hc_claim_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_admin.hc_claims')),
            ],
        ),
    ]
