# Generated by Django 4.2.3 on 2024-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0014_hc_claims_hc_claim_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='committed_allocations',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
