# Generated by Django 4.2.3 on 2024-03-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0016_contacts3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts3',
            old_name='contract_selectable',
            new_name='contact_selectable',
        ),
    ]
