# Generated by Django 4.2.3 on 2024-03-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0018_rename_supplier_committed_quotes_supplierid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committed_quotes',
            name='supplierId',
            field=models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contract_admin.contacts3'),
        ),
    ]
