# Generated by Django 4.2.3 on 2024-03-19 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0019_alter_committed_quotes_supplierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_pk', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_selectable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='committed_quotes',
            name='supplierId',
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS contract_admin_contacts3;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
