# Generated by Django 4.2.3 on 2024-03-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0020_contacts_remove_committed_quotes_supplierid_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS contract_admin_contacts3;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='committed_quotes',
            name='contact_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract_admin.contacts'),
            preserve_default=False,
        ),
    ]
