# Generated by Django 4.2.3 on 2024-03-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0021_delete_contacts3_committed_quotes_contact_pk'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Contacts3',
        # ),
        migrations.AlterField(
            model_name='committed_quotes',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
