# Generated by Django 4.2.3 on 2024-03-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0022_delete_contacts3_alter_committed_quotes_pdf'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Contacts3',
        # ),
    ]
