# Generated by Django 4.2.3 on 2024-03-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_admin', '0023_delete_contacts3'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Contacts3',
        # ),
        migrations.RenameField(
            model_name='committed_allocations',
            old_name='description',
            new_name='notes',
        ),
    ]
